server {
  listen 8080;
  root /usr/share/nginx/html;

  location /api/control/ {
    proxy_pass http://control-api:80/;
  }

  location /api/inference/ {
    proxy_pass http://inference:80/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
