apiVersion: batch/v1
kind: Job
metadata:
  name: make-mlflow-bucket
  namespace: miniature-train
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  activeDeadlineSeconds: 300
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      containers:
        - name: mc
          image: minio/mc:RELEASE.2024-08-17T01-14-57Z
          command: ["/bin/sh", "-c"]
          args: ["mc alias set store http://object-store:9000 $MINIO_USER $MINIO_PASSWORD && mc mb -p store/miniature-train/mlflow"]
          env:
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: object-store
                  key: root-user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: object-store
                  key: root-password
          resources:
            requests:
              cpu: "100m"
              memory: 128Mi
            limits:
              cpu: "500m"
              memory: 512Mi
