apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-api
  namespace: miniature-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-api
  template:
    metadata:
      labels:
        app: control-api
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      serviceAccountName: control-api
      containers:
        - name: api
          image: miniature-train/control-api:v0.24.0
          env:
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_DB
              value: mt
            - name: POSTGRES_USER
              value: mt
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: control-api
                  key: database-password
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
          resources:
            requests:
              cpu: "500m"
              memory: 512Mi
            limits:
              cpu: "1000m"
              memory: 1Gi
