apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-api-secrets
  namespace: miniature-train
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-store
    kind: ClusterSecretStore
  target:
    name: control-api
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: miniature-train/control-api
        property: database-password
    - secretKey: registry-token
      remoteRef:
        key: miniature-train/control-api
        property: registry-token
