apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: object-store-secrets
  namespace: miniature-train
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-store
    kind: ClusterSecretStore
  target:
    name: object-store
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: miniature-train/object-store
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: miniature-train/object-store
        property: root-password
